# Generated by Django 6.0.5 on 2026-05-26 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='resume',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='resume',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
