# Generated by Django 5.1.4 on 2026-06-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resume_options_remove_resume_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='summary',
        ),
    ]
