# Generated by Django 5.1.4 on 2026-06-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_remove_resume_job_title_remove_resume_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='last_name',
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
