# Generated by Django 5.1.4 on 2026-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_remove_resume_first_name_remove_resume_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='active_sections',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of active section ids'),
        ),
    ]
